
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecommerce
    username: user01
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools: <1 key>
  thymeleaf: 
logging: